# Site settings
title: Marius Kristensen Blog
email: your-email@domain.com
description: "My rants about random things i care about."
baseurl: ""
url: "http://blog.suiram.org"
githubusername: crea1
twitterusername: marius_lzm


# Build settings
markdown: kramdown
permalink: pretty
